package Typist::Struct::Base;
use v5.40;

our $VERSION = '0.01';

# Immutable base class for struct instances.
# Subclasses are generated at runtime by the `struct` keyword.

# Immutable update: returns a new instance with specified fields changed.
sub with ($self, %updates) {
    my $meta = $self->_typist_struct_meta;
    my %all_fields = (%{$meta->{required}}, %{$meta->{optional}});

    # Validate field names
    for my $key (keys %updates) {
        die "Unknown field '$key' for struct $meta->{name}\n"
            unless exists $all_fields{$key};
    }

    # Merge: existing values + updates, preserving _type_args
    my %new = %$self;
    @new{keys %updates} = values %updates;

    bless \%new, ref $self;  # _type_args carried over from %$self
}

# Override in generated subclasses
sub _typist_struct_meta ($self) {
    die ref($self) . " must implement _typist_struct_meta()";
}

1;

=encoding utf8

=head1 NAME

Typist::Struct::Base - Immutable base class for struct instances

=head1 SYNOPSIS

    # Typically not used directly -- struct subclasses are generated
    # by the `struct` keyword:
    struct Point => (x => 'Int', y => 'Int');

    my $p = Point(x => 1, y => 2);
    my $q = $p->with(x => 10);      # Point(x => 10, y => 2)

=head1 DESCRIPTION

Provides the immutable update method C<with> for struct instances
generated by L<Typist>'s C<struct> keyword. Each generated struct
class inherits from this base and overrides C<_typist_struct_meta>
to supply field metadata.

=head1 METHODS

=head2 with

    my $new = $obj->with(%field_updates);

Returns a new instance of the same struct type with the specified
fields replaced. Dies if an unknown field name is given.

=head2 _typist_struct_meta

    my $meta = $obj->_typist_struct_meta;

Returns a hashref with keys C<name>, C<required>, and C<optional>
describing the struct's field schema. Must be overridden by generated
subclasses.

=head1 SEE ALSO

L<Typist>, L<Typist::Type::Struct>

=cut
